pages:
  stage: deploy
  script:
    - bundle install
    - bundle exec jekyll build -d public
    - cp ./public/.well-known/acme-challenge/lj4vkMGHWyxMDc2QScZncBHiUCoZoDXkpxnuO6gAARE.html ./public/.well-known/acme-challenge/lj4vkMGHWyxMDc2QScZncBHiUCoZoDXkpxnuO6gAARE
  when: manual
  only:
    - release
  artifacts:
    paths:
    - public
